"""Record REAL pipeline runs and embed them in the UI as a labelled transcript.

The UI prefers a live backend (`boxoffice serve`). When it is opened as a plain
file there is no backend, so it plays a transcript instead. That transcript must
not be hand-written prose that only looks like output: it is generated here by
executing the actual pipeline and capturing exactly what came back, then
injected into `boxoffice/ui/index.html` between the TRANSCRIPT markers.

    python scripts/record_transcript.py                 # offline snapshot
    BOX_TRANSPORT=mcp python scripts/record_transcript.py

The UI labels the result with the transport and timestamp recorded here, so a
judge can always see whether they are looking at a live run or a replay.
"""

from __future__ import annotations

import asyncio
import json
import os
import re
import sys
import time
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO))
os.environ.setdefault("BOX_IN_MEMORY_STATE", "true")

from boxoffice import clickhouse_tools  # noqa: E402
from boxoffice.config import settings  # noqa: E402
from boxoffice.main import ask  # noqa: E402

UI = REPO / "boxoffice" / "ui" / "index.html"
BEGIN = "/* == TRANSCRIPT:BEGIN (generated by scripts/record_transcript.py) == */"
END = "/* == TRANSCRIPT:END == */"

QUESTIONS = [
    ("grounded", "Which genres underperformed in 1999 versus 1998, and which titles dragged the worst one down?"),
    ("abstain_no_rows", "Which genres underperformed in 2021 versus 2020?"),
    ("abstain_unsupported", "What was our total APAC streaming revenue last quarter?"),
]

# A prompt-injection style query, run through the same tool the agent uses.
INJECTION_SQL = "SELECT * FROM url('http://169.254.169.254/latest/meta-data/', 'CSV')"
CROSS_DB_SQL = "SELECT count(*) FROM system.users"


def main() -> int:
    scenarios = {}
    for key, question in QUESTIONS:
        out = asyncio.run(ask(question, use_llm=False))
        scenarios[key] = {"question": question, "result": out}
        print(f"{key}: abstained={out['abstained']} guardrails={len(out['guardrails'])} "
              f"traces={len([t for t in out['traces'] if t])}")

    clickhouse_tools.bind_run("transcript-guardrail")
    guardrail = {
        "injection": {"sql": INJECTION_SQL, "result": clickhouse_tools.run_clickhouse_sql(INJECTION_SQL, note="prompt-injected exfiltration attempt")},
        "cross_database": {"sql": CROSS_DB_SQL, "result": clickhouse_tools.run_clickhouse_sql(CROSS_DB_SQL, note="query outside the allowed data scope")},
        "write": {"sql": "DROP TABLE imdb.movies", "result": clickhouse_tools.run_clickhouse_sql("DROP TABLE imdb.movies", note="write attempt")},
    }
    for name, entry in guardrail.items():
        print(f"guardrail {name}: {entry['result']['status']} - {entry['result'].get('reason')}")

    payload = {
        "recorded_at": time.strftime("%Y-%m-%d %H:%M:%S %z"),
        "transport": settings.transport,
        "scenarios": scenarios,
        "guardrail": guardrail,
    }
    block = f"{BEGIN}\n  var TRANSCRIPT = {json.dumps(payload, indent=2, default=str)};\n  {END}"

    html = UI.read_text()
    pattern = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.S)
    if not pattern.search(html):
        print(f"ERROR: markers not found in {UI}", file=sys.stderr)
        return 2
    UI.write_text(pattern.sub(lambda _: block, html))
    print(f"\nembedded transcript ({len(block)} bytes) into {UI}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
